In [3]:
import pandas as pd
import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq
import os

In [2]:
#IMPORTANTE: utilize os dados de 2 meses para evitar a sobrecarga do programa!

import pandas as pd

arquivo1=pd.read_csv("C:\\Users\\diogo.durao\\Documents\\202501_NovoBolsaFamilia.csv", sep=";", encoding="latin-1") #caminhos dos arquivos
arquivo2=pd.read_csv("C:\\Users\\diogo.durao\\Documents\\202502_NovoBolsaFamilia.csv", sep=";", encoding="latin-1")

df_pandas=pd.concat([arquivo1,arquivo2])

display(df_pandas.head())

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
0,202501,202308,SP,7071,SANTOS,***.085.106-**,2.064389e+10,FERNANDA RAMOS TEIXEIRA,"650,00"
1,202501,202309,SP,7071,SANTOS,***.085.106-**,2.064389e+10,FERNANDA RAMOS TEIXEIRA,"650,00"
2,202501,202310,SP,7071,SANTOS,***.085.106-**,2.064389e+10,FERNANDA RAMOS TEIXEIRA,"650,00"
3,202501,202311,SP,7071,SANTOS,***.085.106-**,2.064389e+10,FERNANDA RAMOS TEIXEIRA,"650,00"
4,202501,202312,SP,7071,SANTOS,***.085.106-**,2.064389e+10,FERNANDA RAMOS TEIXEIRA,"650,00"

In [1]:
import polars as pl

arquivo1=pl.read_csv("C:\\Users\\diogo.durao\\Documents\\202501_NovoBolsaFamilia.csv", separator=";", encoding="latin-1") #caminhos dos arquivos
arquivo2=pl.read_csv("C:\\Users\\diogo.durao\\Documents\\202502_NovoBolsaFamilia.csv", separator=";", encoding="latin-1")

df_polars=pl.concat([arquivo1,arquivo2])

display(df_polars.head())

shape: (5, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202308     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202309     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202310     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202311     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202312     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [4]:
arquivo_csv2 = 'C:\\Users\\diogo.durao\\Documents\\202501_NovoBolsaFamilia.csv'
arquivo_parquet2 = '202501_NovoBolsaFamilia_POLARS.parquet'

# 1. scan_csv() apenas cria o plano (LazyFrame)
lazy_query = pl.scan_csv(arquivo_csv2, separator=';', encoding='utf8-lossy')

# 2. sink_parquet() executa o plano em modo streaming
#    e salva o resultado direto no disco.
lazy_query.sink_parquet(arquivo_parquet2)

print(f"Arquivo '{arquivo_csv2}' convertido para '{arquivo_parquet2}' com sucesso!")

Arquivo 'C:\Users\diogo.durao\Documents\202501_NovoBolsaFamilia.csv' convertido para '202501_NovoBolsaFamilia_POLARS.parquet' com sucesso!